### ISSUE TITLE
desktop\php\wes.php : appel wes_analogique.php

### ISSUE THREAD

**Issue by dginhoux** [guenneguezt/plugin-wes#1]
Il manque dans le fichier desktop\php\wes.php un appel au fichier desktop\php\wes_analogique.php.
Ceci a rajouter vers la ligne 290 : 
<?php include_file('desktop', 'wes_analogique', 'php', 'wes'); ?>

Sans ceci, impossible d'éditer un équipement de type wes_analogique

**Comment by dginhoux** [comment]
A rajouter : `<?php include_file('desktop', 'wes_analogique', 'php', 'wes'); ?>`

**Comment by ghost** [comment]
Bien vu ;-)
Corrigé et publié
