### ISSUE TITLE
Nom du plugin

### ISSUE THREAD

**Issue by cyrilphoenix71** [guenneguezt/plugin-wes#11]
Le nom du plugin doit respecter la norme XyyyyXyyyy

ex :

AndroidRemoteControl

veolia_eau doit devenir VeoliaEau

**Comment by ghost** [comment]
Une modification de nom de plugin est très lourde car elle a pour conséquence dans Jeedom de faire changer le nom des Objets...
En therme de retro-compatibilité c'est quasi impossible tant que ce n'est pas intégré au core.
