### ISSUE TITLE
unités pour les valeurs retournes par le WES

### ISSUE THREAD

**Issue by bricher** [guenneguezt/plugin-wes#3]
Bonjour,

Il serait souhaitable que les unités délarées pour les infos du WES soients corrigées : 
- les index devraient être en Wh (et non en W)
- la puissance apparente devrait être en VA (et non en W, il y a une affaire de cos phi entre les deux)

ou alors avoir accès aux unités. Bizarrement c'est possible pour certaines rubriques (1-wire, pinces ampéremétriques...) et pas pour d'autres (compteur et téléinfo). Pouvoir paramétrer toutes les unités réglerait le problème...
En restant à votre disposition en cas de question et avec mes remerciements, cordialement
Bruno Richer

**Comment by ghost** [comment]
Bonjour,

Pris en compte pour la prochaine version, mais je suis en train de réécrire une grande partie du plugin donc c'est pas simple.
En effet, j'utilise un système de sous class que l'équipe Jeedom n'a pas prévu d'utiliser. Il y a donc des effets de bords actuellement.

A+
Thomas
